"""empty message

Revision ID: 0f1d9d319c48
Revises: 2168b1bd397a
Create Date: 2022-03-30 15:44:17.813974

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f1d9d319c48"
down_revision = "2168b1bd397a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geolocation",
        sa.Column("ip_address", sa.String(length=16), nullable=False),
        sa.Column("country_code", sa.String(length=5), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.DECIMAL(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.DECIMAL(precision=10, scale=7), nullable=True),
        sa.Column("mystery_value", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("ip_address"),
    )
    op.create_index(
        op.f("ix_geolocation_ip_address"), "geolocation", ["ip_address"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geolocation_ip_address"), table_name="geolocation")
    op.drop_table("geolocation")
    # ### end Alembic commands ###
