"""empty message

Revision ID: 2168b1bd397a
Revises: 45aa31cad243
Create Date: 2022-03-30 15:41:38.134952

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2168b1bd397a"
down_revision = "45aa31cad243"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
