"""empty message

Revision ID: 44309677bf69
Revises: 0f1d9d319c48
Create Date: 2022-03-30 19:03:53.991378

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "44309677bf69"
down_revision = "0f1d9d319c48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "geolocation", sa.Column("country", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("geolocation", "country")
    # ### end Alembic commands ###
