"""Create the initial Database

Revision ID: 45aa31cad243
Revises: 
Create Date: 2022-03-30 13:57:31.683323

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45aa31cad243"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geolocation",
        sa.Column("ip_address", sa.String(length=16), nullable=False),
        sa.Column("country_code", sa.String(length=5), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.DECIMAL(precision=7), nullable=True),
        sa.Column("longitude", sa.DECIMAL(precision=7), nullable=True),
        sa.Column("mystery_value", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("ip_address"),
    )
    op.create_index(
        op.f("ix_geolocation_ip_address"), "geolocation", ["ip_address"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geolocation_ip_address"), table_name="geolocation")
    op.drop_table("geolocation")
    # ### end Alembic commands ###
