version: '3.8'

services:
  geolocation-service:
    container_name: geolocation-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres
    hostname: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

